server:
  port: 80
debug: false
logging:
  level:
    root: info
  file: /local/user/app-prd.log

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: mysql://jdbc:155.32.55.88:3307/prd
    username: root1
    password: 123456@!!

mall:
  config:
    name: 优美商城
    description: 这是一家化妆品特卖商城
    hot-sales: 20
    show-advert: true
